# Generated by Django 5.0.2 on 2024-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('website_url', models.URLField()),
                ('logo_local', models.ImageField(upload_to='media/company_logo_og/')),
                ('logo_ext_url', models.URLField()),
            ],
        ),
    ]
