# Generated by Django 5.0.2 on 2024-03-04 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website_url', models.URLField()),
                ('logo', models.ImageField(upload_to='certif_provider_logo_og/')),
            ],
            options={
                'verbose_name': 'Certification Provider',
                'verbose_name_plural': 'Certification Providers',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'ordering': ('period_start',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('speaking', models.CharField(choices=[('Beginner', 'Beginner'), ('lower_elementary', 'Lower Elementary'), ('upper_elementary', 'Upper Elementary'), ('lower_intermediate', 'Lower Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('lower_advanced', 'Lower Advanced'), ('upper_advanced', 'Upper Advanced'), ('fluent', 'Fluent'), ('proficient', 'Proficient'), ('expert', 'Expert / Native')], max_length=30)),
                ('reading', models.CharField(choices=[('Beginner', 'Beginner'), ('lower_elementary', 'Lower Elementary'), ('upper_elementary', 'Upper Elementary'), ('lower_intermediate', 'Lower Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('lower_advanced', 'Lower Advanced'), ('upper_advanced', 'Upper Advanced'), ('fluent', 'Fluent'), ('proficient', 'Proficient'), ('expert', 'Expert / Native')], max_length=30)),
                ('writing', models.CharField(choices=[('Beginner', 'Beginner'), ('lower_elementary', 'Lower Elementary'), ('upper_elementary', 'Upper Elementary'), ('lower_intermediate', 'Lower Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('lower_advanced', 'Lower Advanced'), ('upper_advanced', 'Upper Advanced'), ('fluent', 'Fluent'), ('proficient', 'Proficient'), ('expert', 'Expert / Native')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=700)),
                ('phone', models.CharField(max_length=18)),
                ('mail', models.EmailField(max_length=254)),
                ('trainnings', models.CharField(max_length=50)),
                ('main_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='skill_categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='strengths_logo/')),
            ],
            options={
                'verbose_name': 'Strength',
                'verbose_name_plural': 'Strengths',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_ext_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_local',
            field=models.ImageField(upload_to='company_logo_og/'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('expiration_date', models.DateField(blank=True)),
                ('get_date', models.DateField(blank=True)),
                ('certification_file', models.FileField(upload_to='certifications/')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.certificationprovider')),
            ],
            options={
                'ordering': ('get_date',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_last', models.BooleanField()),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.company')),
            ],
            options={
                'ordering': ('period_start',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skill_group', models.CharField(choices=[('platform_tool_software', 'Platforms, Tools and Software'), ('language', 'Programming Languages')], default='platform_tool_software')),
                ('level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], default='INTERMEDIATE')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.skillcategory')),
            ],
        ),
    ]
