# Generated by Django 5.0.2 on 2024-03-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_certificationprovider_education_language_me_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name': 'Me', 'verbose_name_plural': 'Me'},
        ),
        migrations.AddField(
            model_name='education',
            name='sigle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
