# Generated by Django 5.0.2 on 2024-03-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_alter_me_options_education_sigle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=700)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('online_url', models.URLField(blank=True, null=True)),
                ('tech_used', models.CharField(blank=True, max_length=200, null=True)),
                ('is_programming_proj', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
