# Generated by Django 5.0.2 on 2024-03-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
