# Generated by Django 5.0.2 on 2024-03-09 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_alter_certification_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='icon',
            field=models.ImageField(upload_to='strengths_logo/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
