# Generated by Django 5.0.2 on 2024-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_alter_strength_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='desc',
            field=models.CharField(max_length=350),
        ),
    ]
