# Generated by Django 5.0.2 on 2024-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_alter_strength_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
