# Generated by Django 5.0.2 on 2024-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_alter_certification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
