# Generated by Django 5.0.2 on 2024-03-10 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_alter_certification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='icon',
            field=models.FileField(upload_to='skill_categories/', validators=[django.core.validators.FileExtensionValidator(['png', 'svg'])]),
        ),
    ]
